[package]
name = "sandstorm-collections-app"
version = "1.2.0"
authors = ["David Renshaw <david@sandstorm.io>"]
build = "build.rs"

[[bin]]

name = "server"
path = "src/main.rs"

[build-dependencies]
capnpc = "0.8"

[dependencies]
futures = "0.1"
tokio-core = "0.1"
mio-uds = "0.6"
capnp = "0.8"
capnp-rpc = "0.8"
rustc-serialize = "0.3.19"
url = "1.2"
sandstorm = "0.0.6"
multipoll = { git = "https://github.com/dwrensha/multipoll" }
