[package]
name = "sandstorm-collections-app"
version = "0.1.0"
authors = ["David Renshaw <david@sandstorm.io>"]
build = "build.rs"

[[bin]]

name = "server"
path = "src/main.rs"

[build-dependencies]
capnpc = "0.6"

[dependencies]
gj = "0.2"
gjio = "0.1"
capnp = "0.7"
capnp-rpc = "0.7"
sandstorm = "0.0.1"
